project/calc/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
    path('<str:operacion>/<int:operando1>/<int:operando2>', views.operacion),
]

project/cms/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
    path('new/', views.cms_new, name='cms_new'),
    path('imagen', views.imagen),
    path('loggedIn', views.loggedIn),
    path('logout', views.logout_view),
    path('<str:llave>', views.get_content, name= "get_content"),
    path('modify/<str:llave>', views.cms_modify, name="cms_modify"),

]

project/project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth.views import LoginView as login
from django.conf import settings
from django.conf.urls.static import static
from cms import views

urlpatterns = [
    path('cms/', include('cms.urls')),
    path('calc/', include('calc.urls')),
    path('admin/', admin.site.urls),
    path('login', login.as_view()),
    path('accounts/profile/', views.redirection),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

project/calc/models.py
from django.db import models

# Create your models here.

project/cms/models.py
from django.db import models

class Contenido(models.Model):
    clave = models.CharField(max_length=64)
    valor = models.TextField()

    def __str__(self):
        return self.clave

    def tieneAs(self):
        return 'a' in self.valor

class Comentario(models.Model):
    contenido = models.ForeignKey(Contenido, on_delete=models.CASCADE)
    titulo = models.CharField(max_length=200)
    cuerpo = models.TextField(blank=False)
    fecha = models.DateTimeField('publicado')

    def __str__(self):
        return self.titulo

project/cms/forms.py
from django import forms

from .models import Contenido

class ContenidoForm(forms.ModelForm):

    class Meta:
        model = Contenido
        fields = ('clave', 'valor',)

project/calc/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from . import calculadora


def index(request):
    return HttpResponse("Hola, mundo. Estás en la página de inicio de tu app llamada calc.")

def operacion(request, operacion, operando1, operando2):
    try:
        ans = calculadora.dict[operacion](operando1, operando2)
    except ZeroDivisionError:
        ans = "No division by zero allowed"

    return HttpResponse("Result = {}".format(ans))

project/cms/views.py
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import get_object_or_404
from django.utils import timezone
from django.template import loader
from django.shortcuts import render
from django.contrib.auth import logout
from django.shortcuts import redirect
from .models import Contenido, Comentario
from .forms import ContenidoForm


@csrf_exempt
def get_content(request, llave):
    if request.user.is_authenticated:
        if request.method == "PUT":
            valor = request.body.decode('utf-8')
        elif request.method == "POST":
            action = request.POST['action']
            if action == "Enviar Contenido":
                valor = request.POST['valor']
        if request.method == "PUT" or (request.method == "POST" and action == "Enviar Contenido"):
            try:
                c = Contenido.objects.get(clave=llave)
                c.valor = valor
            except Contenido.DoesNotExist:
                c = Contenido(clave=llave, valor=valor)
            c.save()
        if request.method == "POST" and action == "Enviar Comentario":
            c = Contenido.objects.get(clave=llave)
            titulo = request.POST['titulo']
            cuerpo = request.POST['cuerpo']
            q = Comentario(contenido=c, titulo=titulo, cuerpo=cuerpo, fecha=timezone.now())
            q.save()

        contenido = get_object_or_404(Contenido, clave=llave)
        context = {'contenido': contenido}
        return render(request, 'cms/contenido.html', context)
    else:
        contenido = get_object_or_404(Contenido, clave=llave)
        context = {'contenido': contenido}
        return render(request, 'cms/contenido.html', context)


def index(request):
    content_list = Contenido.objects.all()
    context = {'content_list': content_list}
    if request.user.is_authenticated:
        return render(request, 'cms/index.html', context)
    else:
        return render(request, 'cms/indexNot.html', context)


def loggedIn(request):
    if request.user.is_authenticated:
        logged = "Logged in as " + request.user.username
    else:
        logged = "Not logged in. <a href='/admin/'>Login via admin</a>"
    return HttpResponse(logged)


def logout_view(request):
    logout(request)
    return redirect("/cms/")


def redirection(request):
    return redirect("/cms/")


def imagen(request):
    template = loader.get_template('cms/plantilla.html')
    context = {}
    return HttpResponse(template.render(context, request))


def cms_new(request):
    if request.method == "POST":
        form = ContenidoForm(request.POST)
        if form.is_valid():
            contenido = form.save()
            return redirect('get_content', llave=contenido.clave)
    else:
        form = ContenidoForm()
    return render(request, 'cms/cms_edit.html', {'form': form})


def cms_modify(request, llave):
    contenido = get_object_or_404(Contenido, clave=llave)
    print(contenido)
    if request.method == "POST":
        form = ContenidoForm(request.POST, instance=contenido)
        if form.is_valid():
            contenido = form.save()
            return redirect('get_content', llave=contenido.clave)
    else:
        form = ContenidoForm(instance=contenido)
    return render(request, 'cms/cms_edit.html', {'form': form})

project/cms/templates/cms/IndexNot.html
{% if content_list %}
    <ul>
    {% for content in content_list %}
        <li><a href="/cms/{{ content.clave }}">{{ content.clave }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No contents are available.</p>
{% endif %}
<p>Not logged in. <a href='/admin/'>Login via admin</a></p>

project/cms/templates/cms/cms_edit.html
{% extends 'cms/content.html' %}

{% block contenido %}
    <h2>New content</h2>
    <form method="POST" class="cms-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-info">Guardar</button>
    </form>
{% endblock %}

project/cms/templates/cms/contenido.html
{% extends 'cms/content.html' %}
    {% block contenido %}
        <h1 class="display-4">Llave: {{ contenido.clave }}</h1>
          <p class="lead"> {{ contenido.valor }} </p>
            {% if user.is_authenticated %}
                <button type="button" class="btn btn-light"><a href="{% url 'cms_modify' llave=contenido.clave %}">Modificar contenido</span></a></button>
            {% endif %}
            <hr class="my-4">
            <div class="content container">
                <div class="row">
                    <div class="col-md-8">
                    {% for comentario in contenido.comentario_set.all %}
                        <div class="comentario">
                            <div class="date">
                                {{ comentario.fecha }}
                            </div>
                            <h2>{{ comentario.titulo }}</h2>
                            <p>{{ comentario.cuerpo|linebreaksbr }}</p>
                        </div>
                    {% endfor %}
                    </div>
                </div>
        </div>
    {% endblock %}

project/cms/templates/cms/content.html
{% load static %}
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'cms/bootstrap.min.css' %}">

    <title>CMS de CursosWeb</title>
  </head>
  <body>
        <div class="jumbotron">
            {% block contenido %}
            {% endblock %}
         </div>
        {% if user.is_authenticated %}
            <button type="button" class="btn btn-light"><a href="{% url 'cms_new' %}">Añadir un nuevo contenido</span></a></button>
        {% endif %}
    </body>
</html>

project/cms/templates/cms/index.html
{% if content_list %}
    <ul>
    {% for content in content_list %}
        <li><a href="/cms/{{ content.clave }}">{{ content.clave }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No contents are available.</p>
{% endif %}

    <p>Logged in as {{request.user.username}}</p>

project/cms/templates/cms/plantilla.html
{% load static %}
<img src="{% static "cms/example.jpeg" %}" alt="My image">